export interface AffiliateDetails {
  status: 'confirmed' | 'unverified' | 'needs_verification' | 'none';
  network?: string;
  commission?: {
    type: 'percentage' | 'fixed' | 'mixed';
    value?: number;
    description?: string;
  };
  cookieDays?: number;
  averageOrderValue?: number;
  subscriptionAvailable?: boolean;
  trackingUrl?: string;
  verifiedAt?: string;
  sourceUrl?: string;
  businessType: 'ROASTER' | 'RETAILER' | 'SUBSCRIPTION' | 'BRAND' | 'EQUIPMENT';
  country: string;
  city: string;
}

export const AFFILIATE_REGISTRY: Record<string, AffiliateDetails> = {
  // CONFIRMED AFFILIATE PARTNERS
  'coffee-friend': {
    status: 'confirmed',
    network: 'Adtraction / Awin',
    commission: { type: 'percentage', value: 10.0, description: '10% on coffee beans, 4% on machines' },
    cookieDays: 45,
    averageOrderValue: 230.0,
    subscriptionAvailable: false,
    trackingUrl: 'https://www.coffeefriend.nl/?ref=beandeals',
    verifiedAt: '2026-09-01',
    sourceUrl: 'https://www.coffeefriend.nl/affiliate/',
    businessType: 'RETAILER',
    country: 'Netherlands',
    city: 'Amsterdam',
  },
  'trade-coffee': {
    status: 'confirmed',
    network: 'FlexOffers / Impact',
    commission: { type: 'percentage', value: 8.0, description: '5-8% per sale + bounty' },
    cookieDays: 30,
    averageOrderValue: 75.0,
    subscriptionAvailable: true,
    trackingUrl: 'https://www.drinktrade.com/?ref=beandeals',
    verifiedAt: '2026-09-01',
    sourceUrl: 'https://www.drinktrade.com',
    businessType: 'SUBSCRIPTION',
    country: 'United States',
    city: 'New York, NY',
  },
  'volcanica-coffee': {
    status: 'confirmed',
    network: 'ShareASale (ID: 53789) / Impact',
    commission: { type: 'percentage', value: 10.0, description: '10% base + 5% new partner bonus' },
    cookieDays: 30,
    averageOrderValue: 72.0,
    subscriptionAvailable: true,
    trackingUrl: 'https://volcanicacoffee.com/?ref=beandeals',
    verifiedAt: '2026-09-01',
    sourceUrl: 'https://volcanicacoffee.com/affiliates',
    businessType: 'ROASTER',
    country: 'United States',
    city: 'Atlanta, GA',
  },
  'bean-box': {
    status: 'confirmed',
    network: 'Awin',
    commission: { type: 'percentage', value: 10.0, description: '8-10% per sale' },
    cookieDays: 30,
    averageOrderValue: 75.0,
    subscriptionAvailable: true,
    trackingUrl: 'https://beanbox.com/?ref=beandeals',
    verifiedAt: '2026-09-01',
    sourceUrl: 'https://beanbox.com',
    businessType: 'SUBSCRIPTION',
    country: 'United States',
    city: 'Seattle, WA',
  },
  'lifeboost-coffee': {
    status: 'confirmed',
    network: 'ShareASale (ID: 110103)',
    commission: { type: 'percentage', value: 10.0, description: '5-10% base' },
    cookieDays: 30,
    averageOrderValue: 78.0,
    subscriptionAvailable: true,
    trackingUrl: 'https://lifeboostcoffee.com/?ref=beandeals',
    verifiedAt: '2026-09-01',
    sourceUrl: 'https://lifeboostcoffee.com',
    businessType: 'BRAND',
    country: 'United States',
    city: 'Virginia Beach, VA',
  },
  'coffee-circle': {
    status: 'confirmed',
    network: 'Awin',
    commission: { type: 'percentage', value: 8.0, description: '6-8% per sale' },
    cookieDays: 30,
    averageOrderValue: 60.0,
    subscriptionAvailable: true,
    trackingUrl: 'https://www.coffeecircle.com/?ref=beandeals',
    verifiedAt: '2026-09-01',
    sourceUrl: 'https://www.coffeecircle.com',
    businessType: 'RETAILER',
    country: 'Germany',
    city: 'Berlin',
  },
  'pact-coffee': {
    status: 'confirmed',
    network: 'Awin',
    commission: { type: 'percentage', value: 5.0, description: '2-5% per subscription' },
    cookieDays: 30,
    averageOrderValue: 45.0,
    subscriptionAvailable: true,
    trackingUrl: 'https://www.pactcoffee.com/?ref=beandeals',
    verifiedAt: '2026-09-01',
    sourceUrl: 'https://www.pactcoffee.com',
    businessType: 'SUBSCRIPTION',
    country: 'United Kingdom',
    city: 'London',
  },
  'koa-coffee': {
    status: 'confirmed',
    network: 'ShareASale',
    commission: { type: 'percentage', value: 15.0, description: '10-15% per sale' },
    cookieDays: 45,
    averageOrderValue: 95.0,
    subscriptionAvailable: true,
    trackingUrl: 'https://www.koacoffee.com/?ref=beandeals',
    verifiedAt: '2026-09-01',
    sourceUrl: 'https://www.koacoffee.com',
    businessType: 'ROASTER',
    country: 'United States',
    city: 'Captain Cook, HI',
  },
  'fresh-roasted-coffee': {
    status: 'confirmed',
    network: 'ShareASale / CJ',
    commission: { type: 'percentage', value: 8.0, description: '8% per sale' },
    cookieDays: 30,
    averageOrderValue: 60.0,
    subscriptionAvailable: true,
    trackingUrl: 'https://www.freshroastedcoffee.com/?ref=beandeals',
    verifiedAt: '2026-09-01',
    sourceUrl: 'https://www.freshroastedcoffee.com',
    businessType: 'ROASTER',
    country: 'United States',
    city: 'Sunbury, PA',
  },
  'origin-coffee-roasters': {
    status: 'confirmed',
    network: 'Awin',
    commission: { type: 'percentage', value: 5.0, description: '5% per sale' },
    cookieDays: 30,
    averageOrderValue: 50.0,
    subscriptionAvailable: true,
    trackingUrl: 'https://www.origincoffee.co.uk/?ref=beandeals',
    verifiedAt: '2026-09-01',
    sourceUrl: 'https://www.origincoffee.co.uk',
    businessType: 'ROASTER',
    country: 'United Kingdom',
    city: 'Helston',
  },
  'blue-tokai-coffee': {
    status: 'confirmed',
    network: 'EarnKaro / Direct',
    commission: { type: 'percentage', value: 8.0, description: '5-8% per sale' },
    cookieDays: 30,
    averageOrderValue: 20.0,
    subscriptionAvailable: true,
    trackingUrl: 'https://bluetokaicoffee.com/?ref=beandeals',
    verifiedAt: '2026-09-01',
    sourceUrl: 'https://bluetokaicoffee.com',
    businessType: 'ROASTER',
    country: 'India',
    city: 'New Delhi',
  },

  // UNVERIFIED DIRECT ROASTERS (Listed in Directory for SEO & Discovery)
  'onyx-coffee-lab': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'United States',
    city: 'Rogers, AR',
    subscriptionAvailable: true,
  },
  'sey-coffee': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'United States',
    city: 'Brooklyn, NY',
    subscriptionAvailable: true,
  },
  'square-mile-coffee-roasters': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'United Kingdom',
    city: 'London',
    subscriptionAvailable: true,
  },
  'verve-coffee-roasters': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'United States',
    city: 'Santa Cruz, CA',
    subscriptionAvailable: true,
  },
  'stumptown-coffee-roasters': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'United States',
    city: 'Portland, OR',
    subscriptionAvailable: true,
  },
  'heart-coffee-roasters': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'United States',
    city: 'Portland, OR',
    subscriptionAvailable: true,
  },
  'olympia-coffee-roasters': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'United States',
    city: 'Olympia, WA',
    subscriptionAvailable: true,
  },
  'proud-mary-coffee': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'United States',
    city: 'Portland, OR',
    subscriptionAvailable: true,
  },
  'counter-culture-coffee': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'United States',
    city: 'Durham, NC',
    subscriptionAvailable: true,
  },
  'equator-coffees': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'United States',
    city: 'San Rafael, CA',
    subscriptionAvailable: true,
  },
  'intelligentsia-coffee': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'United States',
    city: 'Chicago, IL',
    subscriptionAvailable: true,
  },
  'the-barn': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'Germany',
    city: 'Berlin',
    subscriptionAvailable: true,
  },
  'la-cabra': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'Denmark',
    city: 'Aarhus',
    subscriptionAvailable: true,
  },
  '49th-parallel': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'Canada',
    city: 'Vancouver',
    subscriptionAvailable: true,
  },
  'friedhats-coffee': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'Netherlands',
    city: 'Amsterdam',
    subscriptionAvailable: true,
  },
  'lot61-coffee-roasters': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'Netherlands',
    city: 'Amsterdam',
    subscriptionAvailable: true,
  },
  'five-elephant': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'Germany',
    city: 'Berlin',
    subscriptionAvailable: true,
  },
  'tim-wendelboe': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'Norway',
    city: 'Oslo',
    subscriptionAvailable: true,
  },
  'glitch-coffee': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'Japan',
    city: 'Tokyo',
    subscriptionAvailable: false,
  },
  'kurasu': {
    status: 'unverified',
    businessType: 'RETAILER',
    country: 'Japan',
    city: 'Kyoto',
    subscriptionAvailable: true,
  },

  // FRANCE
  'cafes-pfaff': {
    status: 'confirmed',
    network: 'Kwanko / Direct',
    commission: { type: 'percentage', value: 5.0, description: '5% per sale' },
    cookieDays: 30,
    averageOrderValue: 45.0,
    subscriptionAvailable: true,
    trackingUrl: 'https://www.cafes-pfaff.com/?ref=beandeals',
    verifiedAt: '2026-09-01',
    sourceUrl: 'https://www.cafes-pfaff.com',
    businessType: 'ROASTER',
    country: 'France',
    city: 'Paris',
  },
  'coutume-cafe': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'France',
    city: 'Paris',
    subscriptionAvailable: true,
  },
  'kb-coffee-roasters': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'France',
    city: 'Paris',
    subscriptionAvailable: true,
  },

  // ITALY
  'gardelli-specialty-coffee': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'Italy',
    city: 'Forlì',
    subscriptionAvailable: false,
  },
  'ditta-artigianale': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'Italy',
    city: 'Florence',
    subscriptionAvailable: true,
  },
  'bugan-coffee-lab': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'Italy',
    city: 'Bergamo',
    subscriptionAvailable: true,
  },

  // GERMANY
  '19grams-coffee': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'Germany',
    city: 'Berlin',
    subscriptionAvailable: true,
  },

  // NETHERLANDS
  'bocca-coffee': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'Netherlands',
    city: 'Amsterdam',
    subscriptionAvailable: true,
  },
  'single-estate-coffee': {
    status: 'unverified',
    businessType: 'ROASTER',
    country: 'Netherlands',
    city: 'The Hague',
    subscriptionAvailable: true,
  },

  // UNITED KINGDOM
  'hasbean-coffee': {
    status: 'confirmed',
    network: 'Awin',
    commission: { type: 'percentage', value: 5.0, description: '3-5% per sale' },
    cookieDays: 30,
    averageOrderValue: 40.0,
    subscriptionAvailable: true,
    trackingUrl: 'https://www.hasbean.co.uk/?ref=beandeals',
    verifiedAt: '2026-09-01',
    sourceUrl: 'https://www.hasbean.co.uk',
    businessType: 'ROASTER',
    country: 'United Kingdom',
    city: 'Staffordshire',
  },
  'climpson-and-sons': {
    status: 'confirmed',
    network: 'Awin',
    commission: { type: 'percentage', value: 4.0, description: '4% per sale' },
    cookieDays: 30,
    averageOrderValue: 42.0,
    subscriptionAvailable: true,
    trackingUrl: 'https://climpsonandsons.com/?ref=beandeals',
    verifiedAt: '2026-09-01',
    sourceUrl: 'https://climpsonandsons.com',
    businessType: 'ROASTER',
    country: 'United Kingdom',
    city: 'London',
  },
  'extract-coffee-roasters': {
    status: 'confirmed',
    network: 'Awin',
    commission: { type: 'percentage', value: 5.0, description: '5% per sale' },
    cookieDays: 30,
    averageOrderValue: 45.0,
    subscriptionAvailable: true,
    trackingUrl: 'https://www.extractcoffee.co.uk/?ref=beandeals',
    verifiedAt: '2026-09-01',
    sourceUrl: 'https://www.extractcoffee.co.uk',
    businessType: 'ROASTER',
    country: 'United Kingdom',
    city: 'Bristol',
  },
};

export function getAffiliateDetails(slug: string): AffiliateDetails {
  return (
    AFFILIATE_REGISTRY[slug] || {
      status: 'unverified',
      businessType: 'ROASTER',
      country: 'United States',
      city: 'Unknown',
    }
  );
}

export function isConfirmedAffiliate(slug: string): boolean {
  return AFFILIATE_REGISTRY[slug]?.status === 'confirmed';
}
