export interface EquipmentItem {
  id: string;
  name: string;
  slug: string;
  brand: string;
  category: 'GRINDER' | 'ESPRESSO_MACHINE' | 'BREWER' | 'KETTLE' | 'SCALE' | 'DRINKWARE' | 'FILTERS_ACCESSORIES' | 'SUBSCRIPTION' | 'GIFT';
  price: number;
  currency: string;
  imageUrl: string;
  affiliateUrl: string;
  affiliateNetwork: string;
  commissionRate: number; // e.g. 8.0 for 8%
  estimatedYieldUsd: number; // (price * commissionRate / 100)
  editorialRating: number;
  description: string;
  features: string[];
  bestFor: string;
  isFeatured?: boolean;
}

export const TOP_EQUIPMENT_ITEMS: EquipmentItem[] = [
  // ☕ ESPRESSO MACHINES
  {
    id: 'breville-barista-express',
    name: 'Breville Barista Express Espresso Machine',
    slug: 'breville-barista-express',
    brand: 'Breville',
    category: 'ESPRESSO_MACHINE',
    price: 699.95,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://www.breville.com/us/en/products/espresso/bes876.html?ref=beandeals',
    affiliateNetwork: 'Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 56.0,
    editorialRating: 4.9,
    description: 'The iconic all-in-one espresso machine featuring an integrated conical burr grinder, dose control, low-pressure pre-infusion, and powerful steam wand.',
    features: ['Integrated Conical Burr Grinder', '15 Bar Italian Pump', 'PID Temperature Control', 'Manual Microfoam Milk Texturing'],
    bestFor: 'Best All-In-One Home Espresso Setup Under $700',
    isFeatured: true,
  },
  {
    id: 'breville-bambino-plus',
    name: 'Breville Bambino Plus Compact Espresso Machine',
    slug: 'breville-bambino-plus',
    brand: 'Breville',
    category: 'ESPRESSO_MACHINE',
    price: 499.95,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://www.breville.com/us/en/products/espresso/bes500.html?ref=beandeals',
    affiliateNetwork: 'Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 40.0,
    editorialRating: 4.8,
    description: 'Ultra-fast 3-second ThermoJet heat-up compact espresso machine featuring hands-free automatic microfoam milk texturing.',
    features: ['ThermoJet 3-Second Heat Up', 'Auto-Milk Microfoam Texturing', '54mm Stainless Steel Portafilter', 'Low Pressure Pre-Infusion'],
    bestFor: 'Best Beginner Compact Espresso Machine Under $500',
    isFeatured: true,
  },
  {
    id: 'gaggia-classic-pro',
    name: 'Gaggia Classic EVO PRO Espresso Machine',
    slug: 'gaggia-classic-pro',
    brand: 'Gaggia',
    category: 'ESPRESSO_MACHINE',
    price: 449.0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://www.gaggia-usa.com/products/gaggia-classic-pro?ref=beandeals',
    affiliateNetwork: 'ShareASale / Impact',
    commissionRate: 7.0,
    estimatedYieldUsd: 31.43,
    editorialRating: 4.7,
    description: 'Italian-made commercial-style home espresso machine featuring a 58mm chrome-plated brass portafilter, 3-way solenoid valve, and commercial steam wand.',
    features: ['58mm Commercial Brass Portafilter', '3-Way Solenoid Valve', 'Commercial 2-Hole Steam Wand', 'Made in Italy'],
    bestFor: 'Best Modder & Traditional Italian Espresso Machine',
    isFeatured: false,
  },

  // ⚙️ GRINDERS
  {
    id: 'baratza-encore-esp',
    name: 'Baratza Encore ESP Electric Coffee & Espresso Grinder',
    slug: 'baratza-encore-esp',
    brand: 'Baratza',
    category: 'GRINDER',
    price: 199.95,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1589396575653-c09c794ff6a6?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://www.baratza.com/en-us/product/encore-esp-acc0851?ref=beandeals',
    affiliateNetwork: 'Awin / Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 16.0,
    editorialRating: 4.9,
    description: 'The gold standard entry-level grinder engineered specifically for both precision espresso micro-steps and clean pour-over filter brewing.',
    features: ['40mm M2 Conical Steel Burrs', 'Micro-step adjustment for espresso (1-20)', 'High-torque quiet DC motor', 'Easy pulse button'],
    bestFor: 'Best Espresso Grinder Under $200',
    isFeatured: true,
  },
  {
    id: 'fellow-ode-gen-2',
    name: 'Fellow Ode Brew Grinder Gen 2',
    slug: 'fellow-ode-gen-2',
    brand: 'Fellow',
    category: 'GRINDER',
    price: 345.0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://fellowproducts.com/products/ode-brew-grinder-gen-2?ref=beandeals',
    affiliateNetwork: 'ShareASale / Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 27.6,
    editorialRating: 4.9,
    description: 'Award-winning countertop filter grinder with 64mm Gen 2 stainless steel flat burrs, anti-static technology, and single-dose loading.',
    features: ['64mm Professional Flat Burrs', 'Ionizer anti-static technology', 'Auto-stop after last bean', '100g load capacity'],
    bestFor: 'Best Pour-Over & Filter Grinder Under $350',
    isFeatured: true,
  },
  {
    id: 'baratza-virtuoso-plus',
    name: 'Baratza Virtuoso+ Conical Burr Coffee Grinder',
    slug: 'baratza-virtuoso-plus',
    brand: 'Baratza',
    category: 'GRINDER',
    price: 249.95,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1589396575653-c09c794ff6a6?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://www.baratza.com/en-us/product/virtuoso-plus-acc0850?ref=beandeals',
    affiliateNetwork: 'Awin / Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 20.0,
    editorialRating: 4.8,
    description: 'High-performance all-purpose grinder featuring 40mm European steel M2 burrs and a digital 40-second pulse timer accurate to 0.1 seconds.',
    features: ['Digital timer display', '40mm European steel conical burrs', 'Backlit clear grounds bin', '40 grind settings'],
    bestFor: 'Best All-Round Home Brew Grinder',
    isFeatured: false,
  },
  {
    id: 'timemore-chestnut-c3',
    name: 'Timemore Chestnut C3 Max Manual Hand Grinder',
    slug: 'timemore-chestnut-c3',
    brand: 'Timemore',
    category: 'GRINDER',
    price: 79.0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://timemore.com/products/chestnut-c3?ref=beandeals',
    affiliateNetwork: 'Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 6.32,
    editorialRating: 4.7,
    description: 'Precision CNC stainless steel Spike-to-Cut (S2C) 660 burr hand grinder providing uniform grind size for travel and home pour-overs.',
    features: ['S2C 660 Stainless Steel Burrs', 'Aluminum alloy body', 'Dual bearing stabilization', 'Compact travel size'],
    bestFor: 'Best Budget Hand Grinder Under $100',
    isFeatured: false,
  },

  // 🫖 KETTLES & 💧 BREWERS
  {
    id: 'fellow-stagg-ekg-kettle',
    name: 'Fellow Stagg EKG Electric Variable Temperature Pour-Over Kettle',
    slug: 'fellow-stagg-ekg-kettle',
    brand: 'Fellow',
    category: 'KETTLE',
    price: 165.0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://fellowproducts.com/products/stagg-ekg-electric-pour-over-kettle?ref=beandeals',
    affiliateNetwork: 'ShareASale / Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 13.2,
    editorialRating: 4.9,
    description: 'Precision gooseneck kettle featuring to-the-degree variable temperature control (135°F to 212°F), built-in brew stopwatch, and ergonomic pour handle.',
    features: ['To-the-degree PID temperature control', '1-hour temperature HOLD option', 'Integrated brew stopwatch', 'Counterbalanced handle'],
    bestFor: 'Best Gooseneck Kettle for Specialty Pour-Over',
    isFeatured: true,
  },
  {
    id: 'moccamaster-kbgv-select',
    name: 'Technivorm Moccamaster KBGV Select 10-Cup Drip Coffee Maker',
    slug: 'moccamaster-kbgv-select',
    brand: 'Technivorm',
    category: 'BREWER',
    price: 359.0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://www.moccamaster.com/kbgv-select?ref=beandeals',
    affiliateNetwork: 'Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 28.72,
    editorialRating: 4.9,
    description: 'Handmade in the Netherlands ECBC-certified drip coffee maker engineered to brew 10 cups of pristine coffee at precise 196°F-205°F temperatures in 6 minutes.',
    features: ['SCA & ECBC Gold Cup Certified', 'Copper boiling element', 'Selector switch for half or full carafe', '5-Year Warranty'],
    bestFor: 'Best Premium Automatic Drip Coffee Maker',
    isFeatured: true,
  },
  {
    id: 'hario-v60-ceramic-set',
    name: 'Hario V60 Ceramic Coffee Dripper & Glass Server Set',
    slug: 'hario-v60-ceramic-set',
    brand: 'Hario',
    category: 'BREWER',
    price: 38.0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://www.hario-usa.com/products/v60-ceramic-set?ref=beandeals',
    affiliateNetwork: 'Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 3.04,
    editorialRating: 4.8,
    description: 'The Japanese classic 60-degree cone pour-over dripper with spiral ribs allowing maximum coffee bed expansion during brewing.',
    features: ['High-fired Arita ceramic construction', '60-degree cone shape', 'Spiral interior ridges', 'Heat-resistant glass server'],
    bestFor: 'Best Classic Specialty Pour-Over Setup',
    isFeatured: false,
  },
  {
    id: 'aeropress-clear-coffee-maker',
    name: 'AeroPress Clear Coffee Maker',
    slug: 'aeropress-clear-coffee-maker',
    brand: 'AeroPress',
    category: 'BREWER',
    price: 49.95,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://aeropress.com/products/aeropress-clear?ref=beandeals',
    affiliateNetwork: 'Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 4.0,
    editorialRating: 4.9,
    description: 'Iconic 3-in-1 immersion and pressure coffee maker made from shatterproof crystal-clear Tritan shatter-resistant polymer.',
    features: ['Shatterproof Tritan clear chamber', 'Rapid 1-minute brew time', 'Brews espresso-style shot or 10oz cup', 'Ultra-portable design'],
    bestFor: 'Best Travel & Immersion Coffee Maker',
    isFeatured: true,
  },

  // ⚖️ COFFEE SCALES
  {
    id: 'acaia-pearl-scale',
    name: 'Acaia Pearl Precision Coffee Scale (2021 Model)',
    slug: 'acaia-pearl-scale',
    brand: 'Acaia',
    category: 'SCALE',
    price: 150.0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://acaia.co/products/pearl?ref=beandeals',
    affiliateNetwork: 'ShareASale',
    commissionRate: 8.0,
    estimatedYieldUsd: 12.0,
    editorialRating: 4.9,
    description: 'Laboratory-grade barista scale featuring 0.1g resolution, real-time flow rate indicator, Bluetooth app integration, and lithium-ion USB-C rechargeable battery.',
    features: ['0.1g resolution with ultra-fast response', 'Real-time Flow Rate Indicator', 'Bluetooth companion app connectivity', 'USB-C rechargeable battery'],
    bestFor: 'Best High-Precision Barista & Brew Scale',
    isFeatured: true,
  },
  {
    id: 'timemore-black-mirror-scale',
    name: 'Timemore Black Mirror Basic+ Espresso & Brew Scale',
    slug: 'timemore-black-mirror-scale',
    brand: 'Timemore',
    category: 'SCALE',
    price: 59.0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://timemore.com/products/black-mirror-basic-plus?ref=beandeals',
    affiliateNetwork: 'Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 4.72,
    editorialRating: 4.8,
    description: 'Minimalist matte black digital scale with auto-timer function, silicone heat pad, and hidden LED display.',
    features: ['0.1g accuracy', 'Auto-start brew timer', 'USB-C rechargeable lithium battery', 'Water-resistant silicone pad'],
    bestFor: 'Best Value Coffee Scale Under $60',
    isFeatured: false,
  },

  // 🥤 DRINKWARE, BOTTLES, CUPS & MUGS
  {
    id: 'fellow-carter-travel-mug',
    name: 'Fellow Carter Everywhere Vacuum Insulated Travel Mug 16oz',
    slug: 'fellow-carter-travel-mug',
    brand: 'Fellow',
    category: 'DRINKWARE',
    price: 35.0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://fellowproducts.com/products/carter-everywhere-mug?ref=beandeals',
    affiliateNetwork: 'ShareASale / Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 2.8,
    editorialRating: 4.9,
    description: 'Double-wall vacuum insulated stainless steel travel mug featuring a interior ceramic coating that protects taste integrity from metallic flavors.',
    features: ['True Taste Ceramic Coating', 'Thin lip drinkable rim', '12 hours hot / 24 hours cold insulation', 'Leak-proof seal lid'],
    bestFor: 'Best Taste-Safe Vacuum Travel Mug',
    isFeatured: true,
  },
  {
    id: 'keepcup-thermal-reusable-cup',
    name: 'KeepCup Thermal Insulated Stainless Steel Cup 12oz',
    slug: 'keepcup-thermal-reusable-cup',
    brand: 'KeepCup',
    category: 'DRINKWARE',
    price: 28.0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://us.keepcup.com/thermal-12oz?ref=beandeals',
    affiliateNetwork: 'Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 2.24,
    editorialRating: 4.7,
    description: 'Barista-standard reusable double-wall thermal cup designed to fit under espresso machine group heads.',
    features: ['Barista standard size', 'Double wall vacuum insulation', 'Splashproof press-fit lid', 'BPA/BPS free'],
    bestFor: 'Best On-The-Go Barista Reusable Cup',
    isFeatured: false,
  },
  {
    id: 'kinto-cronos-glass-cups',
    name: 'Kinto Cronos Double Wall Glass Coffee Cups 250ml (2-Pack)',
    slug: 'kinto-cronos-glass-cups',
    brand: 'Kinto',
    category: 'DRINKWARE',
    price: 32.0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://kinto-usa.com/products/cronos-double-wall-glass?ref=beandeals',
    affiliateNetwork: 'Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 2.56,
    editorialRating: 4.8,
    description: 'Heat-resistant borosilicate double-wall glass cups creating a floating coffee visual while keeping liquid hot.',
    features: ['Insulated double wall borosilicate glass', 'Ergonomic ring grip design', 'Microwave and dishwasher safe', '250ml ideal for flat whites & pour-over'],
    bestFor: 'Best Double Wall Glass Coffee Cups',
    isFeatured: false,
  },
  {
    id: 'hario-v60-glass-server-bottle',
    name: 'Hario V60 Heatproof Glass Coffee Server Carafe 600ml',
    slug: 'hario-v60-glass-server-bottle',
    brand: 'Hario',
    category: 'DRINKWARE',
    price: 24.0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://www.hario-usa.com/products/v60-glass-server-600ml?ref=beandeals',
    affiliateNetwork: 'Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 1.92,
    editorialRating: 4.8,
    description: 'Japanese heatproof glass serving carafe bottle with silicone lid designed to fit under V60 drippers.',
    features: ['Heatproof Japanese borosilicate glass', 'Measuring markings (2-5 cups)', 'Silicone sealed lid', 'Microwave safe'],
    bestFor: 'Best Coffee Server Bottle & Carafe',
    isFeatured: false,
  },
  {
    id: 'fellow-atmos-vacuum-canister',
    name: 'Fellow Atmos Vacuum Coffee Storage Canister 1.2L',
    slug: 'fellow-atmos-vacuum-canister',
    brand: 'Fellow',
    category: 'DRINKWARE',
    price: 38.0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://fellowproducts.com/products/atmos-vacuum-canister?ref=beandeals',
    affiliateNetwork: 'ShareASale / Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 3.04,
    editorialRating: 4.9,
    description: 'Integrated vacuum pump canister that removes oxygen from bean storage to prevent oxidation and double coffee shelf life.',
    features: ['Integrated vacuum pump lid', 'Green vacuum lock indicator ring', 'Airtight silicone seal', 'Holds up to 16oz / 450g coffee beans'],
    bestFor: 'Best Airtight Vacuum Coffee Canister',
    isFeatured: true,
  },

  // 🧹 FILTERS & ACCESSORIES
  {
    id: 'hario-v60-paper-filters-02',
    name: 'Hario V60 Size 02 Natural Paper Filters (100-Pack)',
    slug: 'hario-v60-paper-filters-02',
    brand: 'Hario',
    category: 'FILTERS_ACCESSORIES',
    price: 10.5,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://www.hario-usa.com/products/v60-paper-filter-02?ref=beandeals',
    affiliateNetwork: 'Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 0.84,
    editorialRating: 4.9,
    description: 'Authentic Tabbed Size 02 white cone paper filters engineered for clean, sediment-free pour-over extraction.',
    features: ['100% natural paper pulp', 'Designed specifically for V60 Size 02', 'Zero paper flavor after rinsing', '100 filters per box'],
    bestFor: 'Best V60 Pour-Over Paper Filters',
    isFeatured: false,
  },
  {
    id: 'chemex-bonded-square-filters',
    name: 'Chemex Unbleached Bonded Square Paper Filters (100-Pack)',
    slug: 'chemex-bonded-square-filters',
    brand: 'Chemex',
    category: 'FILTERS_ACCESSORIES',
    price: 14.5,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://www.chemexcoffeemaker.com/chemex-bonded-filters-square.html?ref=beandeals',
    affiliateNetwork: 'Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 1.16,
    editorialRating: 4.9,
    description: 'Heavyweight specialty cone filters 20-30% thicker than standard filters, removing bitter oils and sediment.',
    features: ['20-30% thicker specialty paper', 'Pre-folded square shape', 'Fits 6, 8, and 10-cup Chemex brewers', 'Compostable & biodegradable'],
    bestFor: 'Best Chemex Specialty Paper Filters',
    isFeatured: false,
  },
  {
    id: 'normcore-calibrated-tamper-58mm',
    name: 'Normcore 58.5mm Spring-Loaded Calibrated Espresso Tamper',
    slug: 'normcore-calibrated-tamper-58mm',
    brand: 'Normcore',
    category: 'FILTERS_ACCESSORIES',
    price: 49.99,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://www.normcorewares.com/products/normcore-58-5mm-spring-loaded-tamper?ref=beandeals',
    affiliateNetwork: 'Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 4.0,
    editorialRating: 4.8,
    description: 'Spring-loaded leveling tamper ensuring 30lbs consistent, level tamping pressure every single shot.',
    features: ['30lb spring-loaded force feedback', 'Automatic leveling plate guide', '58.5mm precision stainless flat base', 'Includes 15lb & 25lb interchangeable springs'],
    bestFor: 'Best Calibrated Precision Espresso Tamper',
    isFeatured: false,
  },
  {
    id: 'fellow-eddy-frothing-pitcher',
    name: 'Fellow Eddy Steaming Milk Frothing Pitcher 18oz',
    slug: 'fellow-eddy-frothing-pitcher',
    brand: 'Fellow',
    category: 'FILTERS_ACCESSORIES',
    price: 35.0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://fellowproducts.com/products/eddy-steaming-pitcher?ref=beandeals',
    affiliateNetwork: 'ShareASale / Impact',
    commissionRate: 8.0,
    estimatedYieldUsd: 2.8,
    editorialRating: 4.8,
    description: 'Ergonomic fluted spout milk pitcher engineered for precise latte art pouring and microfoam swirling.',
    features: ['Sharp fluted pouring spout', 'Handleless ribbon grip or handled options', '304 18/8 stainless steel', '18oz capacity'],
    bestFor: 'Best Latte Art Milk Pitcher',
    isFeatured: false,
  },

  // 📦 SUBSCRIPTIONS
  {
    id: 'atlas-coffee-club-subscription',
    name: 'Atlas Coffee Club World Coffee Tour Subscription',
    slug: 'atlas-coffee-club-subscription',
    brand: 'Atlas Coffee Club',
    category: 'SUBSCRIPTION',
    price: 50.0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop&q=80',
    affiliateUrl: 'https://atlascoffeeclub.com/?ref=beandeals',
    affiliateNetwork: 'ShareASale / Impact',
    commissionRate: 15.0,
    estimatedYieldUsd: 15.0,
    editorialRating: 4.9,
    description: 'A global monthly coffee journey curating single-origin micro-lots from Kenya, Ethiopia, Colombia, Costa Rica, Peru, and Indonesia with picturesque coffee postcards.',
    features: ['New country origin featured every month', 'Custom roast level & grind size', 'Tasting notes & origin postcard included', 'Flexible pause or cancel anytime'],
    bestFor: 'Best World Coffee Discovery Subscription',
    isFeatured: true,
  },
];
